var tableElement = document.querySelector("tbody");
var pElement = document.querySelector("#no-grades");
var gradeTable = new GradeTable(tableElement, pElement);
var headerElement = document.querySelector(".avg-grade");
var pageHeader = new PageHeader(headerElement);
var addForm = document.querySelector("#addform-element");
var updateForm = document.querySelector("#updateform-element");
var gradeForm = new GradeForm(addForm, updateForm);
var app = new App(gradeTable, pageHeader, gradeForm);
app.start();
